
PROCESS BEFORE OUTPUT.
  MODULE S0100_START.
  CALL SUBSCREEN SUBSCREEN1
       INCLUDING GS_SUBSCREEN-REPID GS_SUBSCREEN-DYNNR.

PROCESS AFTER INPUT.
*   MODULE S0100_EXIT AT EXIT-COMMAND.
*   MODULE OK_CODE.

  CALL SUBSCREEN SUBSCREEN1.
