
PROCESS BEFORE OUTPUT.
  MODULE PBO_TITLE.
  CALL SUBSCREEN SUB_SELECT INCLUDING SY-REPID '5000'.

PROCESS AFTER INPUT.

  MODULE ON_EXIT AT EXIT-COMMAND.

  CALL SUBSCREEN SUB_SELECT.

  MODULE PAI_5100.
