*----------------------------------------------------------------------*
***INCLUDE LZFG_HEIZUNG_EINKAUFF01.
*----------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  BILD_INITIALISIEREN
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM bild_initialisieren .

  IF picture_control IS INITIAL.


* Create controls
    CREATE OBJECT container
      EXPORTING
        container_name = 'IMMEOBILD'.

    CREATE OBJECT picture_control
      EXPORTING
        parent = container.

* Set the display mode to 'normal' (0)
    CALL METHOD picture_control->set_display_mode
      EXPORTING
        display_mode = cl_gui_picture=>display_mode_fit.


    DATA:       url TYPE  cndp_url.

* Get URL vom DOkument
    CALL FUNCTION 'DP_PUBLISH_WWW_URL'
      EXPORTING
        objid    = 'Z_IMMEOGEBAUDE_JPG'
        lifetime = cndp_lifetime_transaction
      IMPORTING
        url      = url
      EXCEPTIONS
        OTHERS   = 1.

    IF sy-subrc = 0.
*     Load the picture by using the url generated by the data provider.
      CALL METHOD picture_control->load_picture_from_url_async
        EXPORTING
          url = url.
    ENDIF.

  ENDIF.


ENDFORM.                    " BILD_INITIALISIEREN
*&---------------------------------------------------------------------*
*&      Form  DO_OKCODE
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
*----------------------------------------------------------------------*
FORM do_okcode.
*======================================================================

  DATA:
        ld_okcode TYPE syucomm.

* BODY
  ld_okcode = gd_okcode.
  CLEAR gd_okcode.

  IF ( ld_okcode = reca2_okcode_popup-ok ).
    CLEAR ld_okcode.
    gf_cancel = abap_false.
    LEAVE TO SCREEN 0.
  ENDIF.

  IF ( ld_okcode = reca2_okcode_popup-cancel ).
    CLEAR ld_okcode.
    gf_cancel = abap_true.
    LEAVE TO SCREEN 0.
  ENDIF.

  gd_okcode = ld_okcode.

ENDFORM.                    "do_okcode
