
PROCESS BEFORE OUTPUT.
  MODULE PBO_0100.
  MODULE STATUS_0100.
  CALL SUBSCREEN SUB_AREA_ROOT
                 INCLUDING GS_SUBSCREEN-REPID
                           GS_SUBSCREEN-DYNNR.

PROCESS AFTER INPUT.

  CALL SUBSCREEN SUB_AREA_ROOT.

  MODULE PAI_0100 AT EXIT-COMMAND.
