
PROCESS BEFORE OUTPUT.
  MODULE PBO_1000.
  CALL SUBSCREEN SUB_FLACHE
                 INCLUDING GS_GUI-ANLAGE-REPID
                           GS_GUI-ANLAGE-DYNNR.

PROCESS AFTER INPUT.
  CALL SUBSCREEN SUB_FLACHE.
  MODULE PAI_1000.
